name: Building RODPS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Install deps
      run: |
        sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libharfbuzz-dev libfribidi-dev libssl-dev/unstable
        R --no-save -e "install.packages(c('devtools', 'formatR'), repo='https://mirrors.nju.edu.cn/CRAN')"
    - name: Building package
      run: |
        ./tools/package.sh
